version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: lumina-postgres
    environment:
      POSTGRES_USER: lumina
      POSTGRES_PASSWORD: lumina
      POSTGRES_DB: lumina
    ports:
      - "5435:5432"
    volumes:
      - lumina_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: lumina-pgadmin
    profiles:
      - tools
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lumina.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  lumina_pgdata:
